public class TomarUnVasoDeAgua{ 
  public static void main(String[] args){ 
  
  System.out.println("Me dirijo a la cocina");
  System.out.println("Ubicar el vaso en el que voy a tomar agua");
  System.out.println("Me dirijo la nevera");
  System.out.println("Sacar el jarro de agua");
  System.out.println("Me sirvo el agua en el vaso elegido");
  System.out.println("Procedo a tomar mi vaso de agua");
}

}